name: Trigger auto deployment for roosevelt

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/roosevelt-AutoDeployTrigger-35594634-ba5d-410b-976a-94e170a21594.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ROOSEVELT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ROOSEVELT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ROOSEVELT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: crrsipoc-cmgvawatc8azb7gz.azurecr.io
          registryUsername: ${{ secrets.ROOSEVELT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ROOSEVELT_REGISTRY_PASSWORD }}
          containerAppName: roosevelt
          resourceGroup: DefaultResourceGroup-WUS2
          imageToBuild: crrsipoc-cmgvawatc8azb7gz.azurecr.io/roosevelt:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


